services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: loan-app
    container_name: loan-app
    restart: always
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: loan-app-db
    restart: always
    environment:
      POSTGRES_USER: loan-app-admin
      POSTGRES_PASSWORD: 5y6SG97x1rpW
      POSTGRES_DB: loan-app-db
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx:stable-alpine
    container_name: laravel-nginx
    restart: always
    ports:
      - "8080:8080"
      - "4430:4430"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    depends_on:
      - app

volumes:
  pgdata:
